# Generated by Django 4.1.2 on 2022-10-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_darslik', '0009_practistheme_practis_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practis',
            old_name='question_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='practis',
            name='checking',
        ),
        migrations.RemoveField(
            model_name='practis',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='practis',
            name='question',
        ),
        migrations.RemoveField(
            model_name='practis',
            name='solusion',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practis',
            name='body',
            field=models.FileField(default='s', upload_to='lab/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practis',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.FileField(upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body',
            field=models.FileField(upload_to='maruzalar/'),
        ),
    ]
